---
config:
  layout: elk
---
flowchart TD
subgraph input[" "]
  C@{ shape: lean-r, label: "qc_ref_set"} 
  B@{ shape: lean-r, label: "Sample sheet"}
  CNVM@{ shape: lean-r, label: "cnv_ref_m ; cnv_ref_f ; anno_epic"} 

end
  D@{ shape: rect, label: "QC"} 
  E@{ shape: rect, label: "load idats"} -->  D & F & J

  F@{ shape: rect, label: "ß-value / M-value"} -->  I & K 
  
  J@{ shape: rect, label: "CNV"}
  I@{ shape: rect, label: "MGMT"} 
  K@{ shape: rect, label: "Tumor purity"}

B -.-> E
C -.-> D
CNVM -.-> J
style B color:#0e1609, fill:#cca9dd, stroke:#0e1609
style C color:#0e1609, fill:#cca9dd, stroke:#0e1609
style CNVM color:#0e1609, fill:#cca9dd, stroke:#0e1609
style D color:#0e1609, fill:#b0f2b6, stroke:#0e1609
style E color:#0e1609, fill:#b0f2b6, stroke:#0e1609
style F color:#0e1609, fill:#b0f2b6, stroke:#0e1609
style I color:#0e1609, fill:#b0f2b6, stroke:#0e1609
style J color:#0e1609, fill:#b0f2b6, stroke:#0e1609
style K color:#0e1609, fill:#b0f2b6, stroke:#0e1609

style input fill:none,stroke:none