---
config:
  layout: elk
---
flowchart TB
 subgraph Legend["Legend"]
        
        L2["Parallelised process"]
        L3["Global process"]
        L1["INPUT"]
        L4["Per sample OUTPUT"]
        L5["Global OUTPUT"]
  end
    sample["Sample sheet"] -.-> load["load IDATs"]
    load --> xy["compute XY intensities"] & gs["compute_qc_gs"] & plot["plot QC metrics"]
    db["qc_ref_set"] -.-> plot
    plot --> merge["merge QC metrics"]
    plot -.-> qc_tsv["QC metrics (TSV)"] & qc_pdf["QC report (PDF)"]
    merge -.-> global_tsv["global metrics (TSV)"]
    xy --> sex["control sex"]
    xy -.-> xy_tsv["XY intensities (TSV)"]
    sex -.-> sex_pdf["sex control report (PDF)"] & sex_tsv["sex control (TSV)"]
    gs --> merge_gs["merge_qc_metrics_gs"]
    gs -.-> gs_tsv["QC metrics GS (TSV)"]
    merge_gs --> plot_gs["plot_qc_gs"]
    merge_gs -.-> global_gs["global QC metrics GS (TSV)"]
    plot_gs -.-> global_pdf["Global QC GS plot (PDF)"]

    class sample,db,L1 input
    class load,xy,gs,plot,L2 parallel
    class merge,merge_gs,plot_gs,sex,L3 global
    class qc_tsv,qc_pdf,xy_tsv,gs_tsv,L4 output
    class global_tsv,sex_tsv,sex_pdf,global_gs,global_pdf,L5 globalout

    sample@{ shape: lean-r}
    db@{ shape: lean-r}
    L1@{ shape: lean-r}

    L2@{ shape: processes}
    load@{ shape: processes}
    xy@{ shape: processes}
    gs@{ shape: processes}
    plot@{ shape: processes}
    
    L3@{ shape: rect}
    merge@{ shape: rect}
    merge_gs@{ shape: rect}
    plot_gs@{ shape: rect}
    sex@{ shape: rect}
   
    L4@{ shape: docs}
    qc_tsv@{ shape: docs}
    qc_pdf@{ shape: docs}
    xy_tsv@{ shape: docs}
    gs_tsv@{ shape: docs}

    L5@{ shape: doc}
    global_tsv@{ shape: doc}
    sex_tsv@{ shape: doc}
    sex_pdf@{ shape: doc}
    global_gs@{ shape: doc}
    global_pdf@{ shape: doc}
   
    classDef input fill:#CCA9DD,stroke:#222,color:#111
    classDef parallel fill:#B0F2B6,stroke:#222,color:#111
    classDef global fill:#B3EBF2,stroke:#222,color:#111
    classDef output fill:#B0F2B6,stroke:#222,color:#111
    classDef globalout fill:#B3EBF2,stroke:#222,color:#111